# Copyright (c) 2026 Kevin Dedon.
# SPDX-License-Identifier: MIT

# Build CP/M-8000 for the Commodore 900. See README.md for usage.
.DEFAULT_GOAL := all

include mk/config.mk

.PHONY: all clean unpublish deps help
all: unpublish $(CPMSYS) $(CPMAIMG) $(CPMARIMG) $(CPMBIMG) imagecheck farptrcheck \
     $(UCONCFS) $(UXDOS) $(UCON1) $(UCONCZ) $(UXDOSPOL) $(UCONCS) $(UCONCV) \
     $(UCONCW) $(UDIRG) $(UDIRB) $(USPLIT) $(UCONCR) $(UCONCR2) \
     $(CPMDISKALL)
	@$(if $(wildcard $(KBOOT)),:,echo 'note: no kboot at "$(KBOOT)" -- $(CPMDISK) not built. `make deps DEP=kboot`')

help:
	@printf '%s\n' \
	  'make                 build cpm.sys, drive images and the boot medium' \
	  'make imagecheck      check the generated images' \
	  'make farptrcheck     check the banked-memory invariant in src/bdos' \
	  'make verify-<name>   run one emulator verification target' \
	  'make verify-all      run every verification target but verify-zcc' \
	  'make verify-zcc      rebuild src/app on the machine with DRI ZCC and' \
	  '                     run those binaries; 20 minutes, not in verify-all' \
	  'make cpmlocal        LOCALDIR=<dir> LOCALOUT=<path outside the checkout>:' \
	  '                     a boot medium with extra files you supply' \
	  'make deps            fetch inputs listed in DEPS' \
	  'make clean           remove build products'

# Fetch only when explicitly requested; DEP selects one input from DEPS.
deps:
	sh tools/deps-fetch.sh $(DEP)

# Remove published images before compiling so failed builds do not leave stale outputs.
unpublish:
	@rm -f $(CPMSYS) $(CPMAIMG) $(CPMARIMG) $(CPMBIMG) $(CPMDISKALL)

clean:
	rm -rf build

# Recipes share build.log and scratch names in $(OBJDIR); -j interleaves.
.NOTPARALLEL:

# Check documentation references in the packed images, including program strings.
.PHONY: imagecheck
imagecheck: $(CPMSYS) $(CPMAIMG) $(CPMARIMG) $(CPMBIMG)
	@sh tests/mdcheck.sh $(CPMSYS) $(CPMAIMG) $(CPMARIMG) $(CPMBIMG)

# Caller-space far pointers must be accessed through the memory-copy helpers.
.PHONY: farptrcheck
farptrcheck:
	@python3 tests/farptrcheck.py src/bdos/*.c src/bdos/*.h

# Replace only on content changes to avoid unnecessary banner recompiles.
.PHONY: FORCE
FORCE:
$(OBJDIR)/cpmver.h: FORCE | $(OBJDIR)
	@printf '%s\n' \
	  '/* Generated by Makefile -- do not edit.' \
	  '   Set CPMVER in mk/config.mk; dates come from the build host. */' \
	  '#define SYS_BANNER "\014\n\r\nCPM-Z8000 Version $(CPMVER) $(CPMDATE)$$"' \
	  '#define SYS_COPYRIGHT "\r\nCopyright $(COPYYEAR) OpenCoherent contributors$$"' \
	  > $@.tmp
	@cmp -s $@.tmp $@ || mv $@.tmp $@
	@rm -f $@.tmp

$(OBJDIR)/bdosmisc.o: $(OBJDIR)/cpmver.h

include mk/system.mk
include mk/programs.mk
include mk/images.mk
include tests/images.mk
include tests/verify.mk
