#!/usr/bin/env python3
# Copyright (c) 2026 Kevin Dedon.
# SPDX-License-Identifier: MIT

"""mkblob.py -- turn the linked split-I/D module into an assembler source
file that CPM.SYS carries in its data segment.

    mkblob.py split.mod splitimg.s

build/split.mod is an l.out linked at SPLITMBASE and self-contained: it
resolves every symbol it uses among its own objects, so it is bound to no
CPM.SYS address and cannot go stale against one.  Its loaded image goes
into .prvd here -- the DATA segment, which is the whole point, since the
text segment is the resource that ran out -- and cmain.c copies it into
the module segment at cold boot.

Everything the resident system knows about the module is the fixed
interface header splitent.s puts at offset 0.  This script is where that
contract is enforced: the offsets are checked against the module's own
symbol table after every link, so a change that moves them fails the
build instead of producing a system that jumps into the middle of an
instruction the first time a 0xEE0B tool runs.
"""

import struct
import sys

# Must match src/bios/c900cfg.h.
SPM_MAGIC = 0x5350
SPM_VERS = 1
SPLITMBASE = 0x37000000
SPLITMLIM = 0xE3
HDR = [("spment_", 0), ("sptop_", 16), ("spusp_", 18), ("spufp_", 20)]

L_SHRI, L_PRVI, L_BSSI, L_SHRD, L_PRVD, L_BSSD, L_DEBUG, L_SYM, L_REL = range(9)
SYMSZ = 22			# ldsym: 16 name + 2 type + 4 addr


def die(msg):
    sys.exit("mkblob: %s" % msg)


def gl(b, o):
    """One PDP-order (high word first, each word little-endian) long."""
    return (struct.unpack_from("<H", b, o)[0] << 16) | \
        struct.unpack_from("<H", b, o + 2)[0]


def main():
    if len(sys.argv) != 3:
        die("usage: mkblob.py split.mod splitimg.s")
    modf, outf = sys.argv[1], sys.argv[2]
    b = open(modf, "rb").read()
    if len(b) < 48:
        die("%s: too short for an l.out header" % modf)
    magic, flag, machine, tbase = struct.unpack_from("<hhhh", b, 0)
    if magic != 0o407:
        die("%s: bad l.out magic 0%o" % (modf, magic))
    ssize = [gl(b, 8 + 4 * i) for i in range(9)]

    # The image is copied as one block, so the loaded layout has to be
    # SHRI then PRVD with nothing between them.  ld's baseall() puts
    # PRVI, BSSI and SHRD there when they are non-empty, and BSSI in
    # particular would land in the middle of what we copy.
    for seg, name in ((L_PRVI, "PRVI"), (L_BSSI, "BSSI"), (L_SHRD, "SHRD")):
        if ssize[seg]:
            die("%s: %s is %d bytes; the module image must be SHRI+PRVD "
                "only (see the layout note in this script)"
                % (modf, name, ssize[seg]))

    imglen = ssize[L_SHRI] + ssize[L_PRVD]
    bssoff = imglen
    bsslen = ssize[L_BSSD]
    img = b[tbase:tbase + imglen]
    if len(img) != imglen:
        die("%s: file holds %d image bytes, header says %d"
            % (modf, len(img), imglen))

    # The MMU descriptor crt.s programs stops the segment at SPLITMLIM.
    top = (SPLITMLIM + 1) * 256
    if bssoff + bsslen > top:
        die("module is %d bytes; segment SPLITMSEG stops at %d "
            "(raise SPLITMLIM only if the ROM's segment-1 cells allow it)"
            % (bssoff + bsslen, top))

    # The interface header, checked against the module's own symbols.
    nsym = ssize[L_SYM] // SYMSZ
    symoff = tbase + imglen + ssize[L_DEBUG]
    syms = {}
    for i in range(nsym):
        o = symoff + i * SYMSZ
        nm = b[o:o + 16].split(b"\0")[0].decode("ascii", "replace")
        syms[nm] = gl(b, o + 18)
    for nm, off in HDR:
        want = SPLITMBASE + off
        if nm not in syms:
            die("%s: interface symbol %s is missing (splitent.s)" % (modf, nm))
        if syms[nm] != want:
            die("%s: %s is at 0x%08x, the resident side calls it 0x%08x -- "
                "splitent.s and c900cfg.h SPM_* disagree"
                % (modf, nm, syms[nm], want))
    got = struct.unpack_from(">HH", img, 0)
    if got != (SPM_MAGIC, SPM_VERS):
        die("%s: header words are 0x%04x/0x%04x, expected 0x%04x/0x%04x"
            % (modf, got[0], got[1], SPM_MAGIC, SPM_VERS))

    with open(outf, "w") as f:
        f.write("/ Generated by tools/mkblob.py from %s -- do not edit.\n"
                "/ The linked split-I/D module image, carried in CPM.SYS's\n"
                "/ data segment and copied to SPLITMBASE by cmain.c.\n"
                "/ text %d + data %d = %d bytes, bss %d at +0x%x.\n\n"
                % (modf, ssize[L_SHRI], ssize[L_PRVD], imglen, bsslen, bssoff))
        f.write("\t.prvd\n\t.even\n\n")
        for nm, v in (("spimglen_", imglen), ("spbssoff_", bssoff),
                      ("spbsslen_", bsslen)):
            f.write("\t.globl\t%s\n%s:\n\t.word\t%d\n" % (nm, nm, v))
        f.write("\n\t.globl\tsplitimg_\nsplitimg_:\n")
        for i in range(0, imglen, 16):
            row = img[i:i + 16]
            f.write("\t.byte\t" + ",".join("0x%02x" % c for c in row) + "\n")
    print("mkblob: %s -> %s (%d bytes image + %d bss, %d free in segment)"
          % (modf, outf, imglen, bsslen, top - bssoff - bsslen))


main()
